
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Именно в этом году среди рабочего класса Нью-Йорка зародилось понятие хип-хоп',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Самый богатый рэпер на планете',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Кто одним из первых стал исполнителем жанра Hustle',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Как называлась первая рэп-команда СССР',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Назовите самого популярного рэпера планеты',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Именно столько миллионов долларов зарабатывает рэпер Тимати за год:',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Какой музыкальный лейбл России популярнее остальных?',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'В ремейке какого фильма снялся рэпер Noize MC?',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'В каком коллективе выступал Батишта до начала сольной карьеры?',)") 
conn.commit() 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (,'Назовите известную песню рэпера Lizer',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)1955\n 2)1967\n 3)1974',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Тимати\n 2)Dr.Dre\n 3)Wooteng',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)2pac\n 2)Flo Rida\n 3)Dr.Dre',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Берег слоновой кости\n 2)USSR\n 3)DMJ',)"
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Flo Rida\n 2)Eminem\n 3)Lil pump',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)201\n 2)301\n 3)251',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Gazgolder\n 2)Black Star\n 3)MALFA ',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Розыгрыш\n 2)Экипаж\n 3)Джентельмены удачи ',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Бумбокс\n 2)БАНД’ЭРОС\n 3)Йорш ',)") 
conn.commit() 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (,'1)Black swan\n 2)Blach wall\n 3)Black mirror',)") 
conn.commit() 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'1974',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'Dr.Dre',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'2pac',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'DMJ',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'Eminem',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'201',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'Black Star',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'Розыгрыш',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'БАНД’ЭРОС',)") 
conn.commit()
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(,'Black mirror',)") 
conn.commit()